version: '3.5'
volumes:
  jenkins_data:
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 80:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home